// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesAndReturns.Entities
{
    internal partial class Coupon
    {
        public Coupon()
        {
            Sales = new HashSet<Sale>();
        }

        public int CouponID { get; set; }
        public string CouponIDValue { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int CouponDiscount { get; set; }
        public int SalesOrService { get; set; }

        public virtual ICollection<Sale> Sales { get; set; }
    }
}