// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesAndReturns.Entities
{
    internal partial class Employee
    {
        public Employee()
        {
            SaleRefunds = new HashSet<SaleRefund>();
            Sales = new HashSet<Sale>();
        }

        public int EmployeeID { get; set; }
        public string SocialInsuranceNumber { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string ContactPhone { get; set; }
        public bool Textable { get; set; }
        public string EmailAddress { get; set; }
        public int PositionID { get; set; }

        public virtual ICollection<SaleRefund> SaleRefunds { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}