// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesAndReturns.Entities
{
    internal partial class SaleRefundDetail
    {
        public int SaleRefundDetailID { get; set; }
        public int SaleRefundID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal SellingPrice { get; set; }
        public string Reason { get; set; }

        public virtual Part Part { get; set; }
        public virtual SaleRefund SaleRefund { get; set; }
    }
}