// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesAndReturns.Entities
{
    internal partial class Sale
    {
        public Sale()
        {
            SaleDetails = new HashSet<SaleDetail>();
            SaleRefunds = new HashSet<SaleRefund>();
        }

        public int SaleID { get; set; }
        public DateTime SaleDate { get; set; }
        public int EmployeeID { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal SubTotal { get; set; }
        public int? CouponID { get; set; }
        public string PaymentType { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
        public virtual ICollection<SaleRefund> SaleRefunds { get; set; }
    }
}